#!/bin/sh
# postinstall script for prometheus-node-exporter
# Script executed after the package is installed.

set -e

# summary of how this script can be called:
#        * <postinst> 'configure' <most-recently-configured-version>
#        * <old-postinst> 'abort-upgrade' <new version>
#        * <conflictor's-postinst> 'abort-remove' 'in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> 'abort-deconfigure' 'in-favour'
#          <failed-install-package> <version> 'removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the 'postinst' is called with 'abort-upgrade',
#     'abort-remove' or 'abort-deconfigure'.

SERVICE_NAME=prometheus-rds-exporter
UNIX_USER=prometheus-rds-exporter
HOME_DIRECTORY=/var/lib/${UNIX_USER}

case "$1" in
  configure)

    printf "\033[32mCreate system user\033[0m\n"
    adduser --quiet --system --group --home ${HOME_DIRECTORY} \
            --gecos "Prometheus RDS exporter daemon" ${UNIX_USER}

    printf "\033[32mReload the service unit from disk\033[0m\n"
    systemctl daemon-reload ||:

    printf "\033[32mUnmask the service\033[0m\n"
    systemctl unmask ${SERVICE_NAME} ||:

    printf "\033[32mSet the preset flag for the service unit\033[0m\n"
    systemctl preset ${SERVICE_NAME} ||:

    printf "\033[32mSet the enabled flag for the service unit\033[0m\n"
    systemctl enable ${SERVICE_NAME} ||:

    printf "\033[32mRestart the service unit\033[0m\n"
    systemctl restart ${SERVICE_NAME} ||:
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    :
  ;;

  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
  ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
