{
 "title": "RDS cluster details",
 "description": "RDS cluster details",
 "tags": [
  "dmf",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "Account",
    "query": "label_values(rds_instance_info, aws_account_id)"
   },
   {
    "name": "aws_region",
    "label": "Region",
    "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\"}, aws_region)"
   },
   {
    "name": "cluster_identifier",
    "label": "Cluster",
    "query": "label_values(rds_cluster_info{aws_account_id=~\"$aws_account_id\", aws_region=~\"$aws_region\"}, cluster_identifier)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Engine",
   "type": "stat",
   "description": "Engine",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rds_cluster_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"}\n"
    }
   ]
  },
  {
   "title": "Engine Version",
   "type": "stat",
   "description": "Cluster engine version",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "rds_cluster_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"}\n"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of instances in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",cluster_identifier=~\"$cluster_identifier\"})\n"
    }
   ]
  },
  {
   "title": "Instances class",
   "type": "stat",
   "description": "Number of instances by instance class type",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",cluster_identifier=~\"$cluster_identifier\"}) by (instance_class)\n",
     "legendFormat": "{{ instance_class }}"
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 4 } },
  {
   "title": "Instances",
   "type": "table",
   "description": "List of RDS instances in the clusters",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",cluster_identifier=~\"$cluster_identifier\"}\n"
    }
   ]
  }
 ]
}