// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"

	servicequotas "github.com/aws/aws-sdk-go-v2/service/servicequotas"
	mock "github.com/stretchr/testify/mock"
)

// ServiceQuotasClient is an autogenerated mock type for the ServiceQuotasClient type
type ServiceQuotasClient struct {
	mock.Mock
}

// GetServiceQuota provides a mock function with given fields: ctx, input, optFns
func (_m *ServiceQuotasClient) GetServiceQuota(ctx context.Context, input *servicequotas.GetServiceQuotaInput, optFns ...func(*servicequotas.Options)) (*servicequotas.GetServiceQuotaOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *servicequotas.GetServiceQuotaOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *servicequotas.GetServiceQuotaInput, ...func(*servicequotas.Options)) (*servicequotas.GetServiceQuotaOutput, error)); ok {
		return rf(ctx, input, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *servicequotas.GetServiceQuotaInput, ...func(*servicequotas.Options)) *servicequotas.GetServiceQuotaOutput); ok {
		r0 = rf(ctx, input, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicequotas.GetServiceQuotaOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *servicequotas.GetServiceQuotaInput, ...func(*servicequotas.Options)) error); ok {
		r1 = rf(ctx, input, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceQuotasClient creates a new instance of ServiceQuotasClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceQuotasClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ServiceQuotasClient {
	mock := &ServiceQuotasClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
