global:
  scrape_interval:     30s # Set the scrape interval. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every. The default is every 1 minute.
  scrape_timeout: 10s

# Scrape configuration
scrape_configs:
  - job_name: 'rds-exporter'
    static_configs:
    - targets: ['rds-exporter:9043']
